name: free_api
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  #    localization
  flutter_localizations:
    sdk: flutter
  intl: any


  # design
  cupertino_icons: ^1.0.6
  toastification: ^2.1.0
  l: ^4.0.2
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  pin_code_fields: ^8.0.1
  persistent_bottom_nav_bar: ^6.2.1
  cached_network_image: ^3.3.1
  lottie: ^3.1.2
  device_preview: ^1.2.0
  connectivity_plus: ^6.0.4
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  pinput: ^5.0.0
  google_fonts: ^6.2.1
  animated_toggle_switch: ^0.8.3
  keyboard_dismisser: ^3.0.0
  image_picker: ^1.1.2
  web_socket_channel: ^3.0.1


  # Navigation
  go_router: ^14.2.3

  #  state management
  flutter_riverpod: ^2.5.1
  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.1

  #  Network
  dio: ^5.5.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: any
  flutter_lints: ^3.0.0


flutter_intl:
  enabled: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
